### ISSUE TITLE
mistake in fresnel.t_per_amplitude?

### ISSUE THREAD

**Issue by gapster** [scottprahl/pypolar#3]
I think it's a mistake, but my energy to dig into it is flagging.
My concern was aroused when I was getting values of ts that were >1, and noticing that the figure in the docs "Similar to Hecht Figure 4.41" doesn't really look like that figure.  (It is 4.41 in my edition, but in a newer edition it's 4.49)  I wondered if the difference is immaterial; the amplitudes obey "conservation laws" that are not as simple as r + t = 1, so I tried to make it all work.  I ran out of energy.  I believe there is a mistake, but I can't unambiguously convince myself that it is so.

fresnel.t_per_amplitude has 
ts = 2 * d / (m/n_i)/ (c + d)
which doesn't look correct to me.

while sym_fresnel.t_per_amplitude has
ts = 2 * c / (c + d)
which looks  correct to me. 
 
Thanks for this package.  It has saved me a lot of time.
-gapster

**Comment by scottprahl** [comment]
thanks.  I will look into it.  Way too busy at the moment though.

**Comment by gapster** [comment]
I can easily work around this.   No worries.

**Comment by gapster** [comment]
I think you are right after all.  I'm making sure I understand.  Don't bother approaching this unless you hear from me.
